package com.example.beautysalonwebapp.controller;

import com.example.beautysalonwebapp.entity.User;
import com.example.beautysalonwebapp.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
//@SessionAttributes("phone")
public class demoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;



//    @RequestMapping("/")
//    public String showHomePage(Model model){
//        model.addAttribute("phone", new User());
//        return "greeting";
//    }

    @RequestMapping(value = "/greeting")
    public String helloWorldController(Model model) {
        model.addAttribute("user", "Vika");
        return "greeting";
    }
    @RequestMapping(value = "/all")
    public String allUsers(Model model) {
        Iterable<User> user = userRepository.findAll();
        model.addAttribute("user", user);
        return "all";
    }

    @RequestMapping(value = "/cookie")
    public String cook() {
//        model.addAttribute("phone", phone);
        return "greeting";
    }

    @RequestMapping(value = "/admin")
    public String helloAdmin() {
        return "admin";
    }
    @RequestMapping(value = "/main")
    public String mainpage() {
        return "main";
    }

    @RequestMapping(value = "/about")
    public String aboutpage() {
        return "about";
    }

}
